### ISSUE TITLE
dhclient is deprecated

### ISSUE THREAD

**Issue by frankcrawford** [sshambar/nmutils#10]
I've just found that DHCP has been deprecated by ISC as at the end of 2022, this included dhclient.  See https://www.isc.org/dhcp/

While a client is built into NetworkManager and into systemd-networkd, I'm not sure you can use either of them directly.

An alternate package is https://roy.marples.name/projects/dhcpcd which does seem to be supported and is being looked at as a possible simple replacement by some distributions.

What do you think?

**Comment by sshambar** [comment]
Wow... no, I have heard nothing of this (even through channels like reddit, slashdot, whathaveyou...). I'll have to investigate what NM will use as the "non-internal" solution moving forward, but I'm guessing that dhclient will still be around for a few release cycles to provide opportunity for migration to... something(tm) :)

**Comment by frankcrawford** [comment]
Yeah, I was surprised when I read it the other day too.  Most comments are similar that dhclient will be around for a while and so there is time to work out what to do.

**Comment by SpareSimian** [comment]
Raspberry Pi OS, based on Debian, uses dhcpcd. (I'm using a Pi 4 as a home router with ATT Gbps fiber.) Alas, the version used in Debian is 8.1.2 and upstream recently went to version 10.0.1. So there have been a lot of commits since the Debian version. https://github.com/NetworkConfiguration/dhcpcd

I've had to deploy sqm-scripts, ufw, radvd, ndppd, and a hook script to set up default and source routing tables for each interface. My script calls the multihome script found here to set up the source routes.

https://github.com/DanielG/dhcp-policy-routing

I've run into an issue with dhcpcd not delegating an IPv6 prefix on reboot and requiring a "kick" with a --rebind request but I think it's fixed in the 9.x series and need to rebuild the package with the newer upstream release to confirm.

**Comment by frankcrawford** [comment]
FYI, I've just noticed that Fedora is planning to deprecate dhclient in Fedora F41, i.e. in 6-9 months (they are just about to release F40).

**Comment by sshambar** [comment]
The new update to `08-ipv6-prefix` has support for dhcpcd!  You might want to check the README or `08-ipv6-prefix help` for how to enable dhcpcd support - basically, it requires ipv6.method=ignore, and installing dhcpcd, rdisc6 (ndisc6 package), and either resolvectl or resolvconf for DNS.

dhclient is still used if the config isn't compatible, but the logs should indicate what needs installing (or configs changed :)

New release should close this issue though... :)
